APP_DEBUG = true

DEFAULT_TIMEZONE = Asia/Shanghai

TYPE = mysql
HOSTNAME = {HOSTNAME}
DATABASE = {DATABASE}
USERNAME = {USERNAME}
PASSWORD = {PASSWORD}
HOSTPORT = {HOSTPORT}
CHARSET = {CHARSET}
PREFIX = {PREFIX}