APP_DEBUG = true

DEFAULT_TIMEZONE = Asia/Shanghai

UPLOAD_PUBLIC_URL = {UPLOAD_PUBLIC_URL}

TYPE = mysql
HOSTNAME = {HOSTNAME}
DATABASE = {DATABASE}
USERNAME = {USERNAME}
PASSWORD = {PASSWORD}
HOSTPORT = {HOSTPORT}
CHARSET = {CHARSET}
PREFIX = {PREFIX}