<?php

return [
    [
        'name' => 'plugin_admin',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'saas_appid',
            'role_id',
            'pid',
            'username',
            'password',
            'status',
            'nickname',
            'last_login_ip',
            'last_login_time',
            'delete_time',
            'headimg',
            'is_system',
        ],
    ],
    [
        'name' => 'plugin_ads',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'saas_appid',
            'name',
            'category',
            'title',
            'status',
            'image_url',
            'link_url',
        ],
    ],
    [
        'name' => 'plugin_articles_cate',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'saas_appid',
            'title',
            'status',
            'sort',
        ],
    ],
    [
        'name' => 'plugin_articles',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'saas_appid',
            'cid',
            'title',
            'desc',
            'thumb',
            'status',
            'content',
            'view',
            'virtually_view',
        ],
    ],
    [
        'name' => 'plugin_roles',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'saas_appid',
            'pid',
            'title',
            'rule',
            'is_system',
        ],
    ],
    [
        'name' => 'plugin_tags',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'saas_appid',
            'name',
            'title',
            'status',
            'content',
        ],
    ],
    [
        'name' => 'store_menus',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'path',
            'pid',
            'title',
            'sort',
            'method',
            'is_api',
            'component',
            'auth_params',
            'icon',
            'show',
            'is_system',
            'is_default',
        ],
    ],
    [
        'name' => 'store_app',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'store_id',
            'title',
            'name',
            'url',
            'logo',
            'status',
            'platform',
        ],
    ],
    [
        'name' => 'store',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'title',
            'username',
            'password',
            'status',
            'logo',
            'remarks',
            'copyright_service',
            'copyright_tutorial',
            'last_login_ip',
            'last_login_time',
            'plugins_name',
            'wechat',
            'mini_wechat',
            'douyin',
            'h5',
            'app',
            'other',
            'is_uploadify',
        ],
    ],
    [
        'name' => 'system_admin',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'role_id',
            'pid',
            'username',
            'password',
            'status',
            'nickname',
            'last_login_ip',
            'last_login_time',
            'delete_time',
            'headimg',
            'is_system',
        ],
    ],
    [
        'name' => 'system_admin_log',
        'fields' => [
            'id',
            'create_at',
            'admin_id',
            'role_id',
            'action_name',
            'action_ip',
            'city_name',
            'isp_name',
            'action_type',
            'path',
            'params',
        ],
    ],
    [
        'name' => 'system_admin_role',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'pid',
            'title',
            'rule',
            'is_system',
        ],
    ],
    [
        'name' => 'system_auth_rule',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'path',
            'pid',
            'title',
            'sort',
            'method',
            'is_api',
            'component',
            'auth_params',
            'icon',
            'show',
            'is_system',
            'is_default',
        ],
    ],
    [
        'name' => 'system_config',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'group',
            'value',
            'store_id',
            'saas_appid',
        ],
    ],
    [
        'name' => 'system_upload',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'store_id',
            'saas_appid',
            'uid',
            'cid',
            'title',
            'filename',
            'path',
            'format',
            'size',
            'adapter',
        ],
    ],
    [
        'name' => 'system_upload_cate',
        'fields' => [
            'id',
            'create_at',
            'update_at',
            'store_id',
            'saas_appid',
            'uid',
            'title',
            'dir_name',
            'sort',
            'is_system',
        ],
    ],
];